version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data/registry
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  h2c:
    enabled: true
proxy:
  remoteurl: https://registry-1.docker.io
  username: $USERNAME
  password: $PASSWORD
  ttl: 168h # 7 days of TTL
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3