version: '3.7'
services:
    proxy:
        build: 
            context: ./
            dockerfile: 'Dockerfile'
            args:
                - BUILD_FROM=ghcr.io/rpardini/docker-registry-proxy:0.6.3
        volumes:
          - ./dev_options.json:/data/options.json
